<<<<<<< HEAD
# NOTE: This file is auto generated by OpenAPI Generator 6.6.3-amadeus (https://openapi-generator.tech).
=======
# NOTE: This file is auto generated by OpenAPI Generator 7.0.0-SNAPSHOT (https://openapi-generator.tech).
>>>>>>> 635f7952cec10eecf437886ccd03983b655cd6f2
# Do not edit this file manually.

defmodule OpenapiPetstore.Model.Order do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :petId,
    :quantity,
    :shipDate,
    :status,
    :complete
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :petId => integer() | nil,
    :quantity => integer() | nil,
    :shipDate => DateTime.t | nil,
    :status => String.t | nil,
    :complete => boolean() | nil
  }
end

defimpl Poison.Decoder, for: OpenapiPetstore.Model.Order do
  def decode(value, _options) do
    value
  end
end

