=begin
#OpenAPI Extension generating aliases to maps and arrays as models

#This specification shows how to generate aliases to maps and arrays as models.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
<<<<<<< HEAD
OpenAPI Generator version: 6.6.3-amadeus
=======
OpenAPI Generator version: 7.0.0-SNAPSHOT
>>>>>>> 635f7952cec10eecf437886ccd03983b655cd6f2

=end

module Petstore
  VERSION = '1.0.0'
end
